input {
  file {
    path => "/app/logs/todo-api.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  date {
    match => ["time", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "environment" => "local"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "todo-api-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
